version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: './docker/Dockerfile.dev'
    volumes:
      - './src:/app/src'
      - './test:/app/test'
    ports:
      - '3000:${PORT}'
    env_file:
      - ${APP_ROOT}/Makefile.override
    depends_on:
      mongo:
        condition: service_healthy
      minio:
        condition: service_healthy

networks:
  default:
    name: 'dev-network'
