FROM base-prod as build

COPY . .

RUN yarn build

ENV NODE_ENV=production

RUN yarn install --production --frozen-lockfile --prune \
    && yarn cache clean --force

USER node

FROM node:18-bookworm as prod

WORKDIR /app

COPY --chown=node:node --from=build /app/dist ./dist
COPY --chown=node:node --from=build /app/node_modules ./node_modules

ENV NODE_ENV=production

USER node

CMD ["node", "dist/main.js"]
