name: build-and-push

on:
  push:
    branches:
      - mainx

env:
  AWS_REGION: us-west-2
  IMAGE_NAME: ghcr.io/regmicmahesh/nestjs-cicd-template:${{ github.ref_name }}-${{ github.sha }}
  BASE_IMAGE_NAME: ghcr.io/regmicmahesh/node-18-bookworm:${{ github.ref_name }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: "regmicmahesh"
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Check if package and lock files have changed.
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
          files_yaml: |
            dependencies:
             - package.json
             - yarn.lock

      - name: Build Base Image
        if: steps.changed-files.outputs.dependencies_any_changed == 'true'
        run: make docker/push-base

      - name: Push Image to Production
        run: |
          make docker/push
